# Base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt --verbose

# Copy the rest of the source code
COPY . .

ENV PYTHONPATH=/app
# Expose port for API service
EXPOSE 5000

# Run the inference service
CMD ["python", "src/inference_endpoint/model_endpoint.py"]